swagger.title=Product Service API
swagger.description=API documentation for Product Service
swagger.version=1.0.0

product.create=API to create a new product.
product.getById=API to get product details by product ID.
product.getAll=API to get all available products.
product.update=API to update product details by product ID.
product.delete=API to delete a product by product ID.